// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop_tinyfarm_sim.h for the primary calling header

#ifndef VERILATED_VTOP_TINYFARM_SIM___024ROOT_H_
#define VERILATED_VTOP_TINYFARM_SIM___024ROOT_H_  // guard

#include "verilated.h"


class Vtop_tinyfarm_sim__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_tinyfarm_sim___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_pix,0,0);
        VL_IN8(sim_rst,0,0);
        VL_IN8(ui_mode_sel,1,0);
        VL_IN8(ui_crop_sel,1,0);
        VL_IN8(btn_left,0,0);
        VL_IN8(btn_right,0,0);
        VL_IN8(btn_action,0,0);
        VL_IN8(btn_fulfill,0,0);
        VL_OUT8(sdl_de,0,0);
        VL_OUT8(sdl_r,7,0);
        VL_OUT8(sdl_g,7,0);
        VL_OUT8(sdl_b,7,0);
        VL_OUT8(order_crop_o,1,0);
        VL_OUT8(order_qty_o,1,0);
        VL_OUT8(order_timer_o,4,0);
        CData/*0:0*/ top_tinyfarm_sim__DOT__de;
        CData/*1:0*/ top_tinyfarm_sim__DOT__field_sel;
        CData/*2:0*/ top_tinyfarm_sim__DOT__inv_wheat;
        CData/*2:0*/ top_tinyfarm_sim__DOT__inv_corn;
        CData/*2:0*/ top_tinyfarm_sim__DOT__inv_carrot;
        CData/*2:0*/ top_tinyfarm_sim__DOT__inv_tomato;
        CData/*1:0*/ top_tinyfarm_sim__DOT__order_crop;
        CData/*1:0*/ top_tinyfarm_sim__DOT__order_qty;
        CData/*4:0*/ top_tinyfarm_sim__DOT__order_timer;
        CData/*7:0*/ top_tinyfarm_sim__DOT__score;
        CData/*7:0*/ top_tinyfarm_sim__DOT__lfsr;
        CData/*7:0*/ top_tinyfarm_sim__DOT__paint_r;
        CData/*7:0*/ top_tinyfarm_sim__DOT__paint_g;
        CData/*7:0*/ top_tinyfarm_sim__DOT__paint_b;
        CData/*7:0*/ top_tinyfarm_sim__DOT__game_update__DOT__new_lfsr;
        CData/*2:0*/ top_tinyfarm_sim__DOT__u_left__DOT__sync_ff;
        CData/*2:0*/ top_tinyfarm_sim__DOT__u_right__DOT__sync_ff;
        CData/*2:0*/ top_tinyfarm_sim__DOT__u_action__DOT__sync_ff;
        CData/*2:0*/ top_tinyfarm_sim__DOT__u_fulf__DOT__sync_ff;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__15__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__15__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__16__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__16__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__17__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__17__crop;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__18__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__19__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__20__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__21__Vfuncout;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__22__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__22__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__23__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__23__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__24__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__24__crop;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__25__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__26__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__27__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__28__Vfuncout;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__29__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__29__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__30__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__30__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__31__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__31__crop;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__32__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__33__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__34__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__35__Vfuncout;
    };
    struct {
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__36__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__36__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__37__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__37__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__38__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__38__crop;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__39__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__40__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__41__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__42__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__43__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__44__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__45__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__46__Vfuncout;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__47__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__47__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__48__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__48__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__49__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__49__crop;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__50__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__51__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__52__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__53__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__54__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__55__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__56__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__57__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__58__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__59__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__60__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__61__Vfuncout;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__62__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_r__62__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__63__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_g__63__crop;
        CData/*7:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__64__Vfuncout;
        CData/*1:0*/ __Vfunc_top_tinyfarm_sim__DOT__crop_b__64__crop;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__65__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__66__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__67__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__68__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__69__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__70__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__71__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__72__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__73__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__74__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__75__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__79__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__80__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__81__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__82__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__86__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__87__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__88__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__89__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__93__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__94__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__95__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__96__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__100__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__101__Vfuncout;
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__102__Vfuncout;
    };
    struct {
        CData/*0:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__103__Vfuncout;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_pix__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_OUT16(sdl_sx,9,0);
        VL_OUT16(sdl_sy,9,0);
        SData/*9:0*/ top_tinyfarm_sim__DOT__sx;
        SData/*9:0*/ top_tinyfarm_sim__DOT__sy;
        SData/*9:0*/ top_tinyfarm_sim__DOT__frames_until_tick;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__18__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__18__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__19__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__19__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__20__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__20__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__21__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__21__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__21__w;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__25__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__25__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__26__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__26__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__27__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__27__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__28__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__28__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__28__w;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__32__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__32__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__33__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__33__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__34__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__34__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__35__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__35__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__35__w;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__39__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__39__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__40__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__40__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__41__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__41__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__42__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__42__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__42__w;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__43__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__43__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__44__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__44__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__45__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__45__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__46__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__46__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__50__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__50__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__51__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__51__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__52__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__52__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__53__x;
    };
    struct {
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__53__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__53__w;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__54__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__54__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__55__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__55__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__56__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__56__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__57__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__57__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__57__w;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__58__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__58__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__59__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__59__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__60__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__60__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__61__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__61__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__65__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__65__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__66__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__66__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__67__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__67__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__68__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__68__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__69__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__69__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__70__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__70__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__71__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__71__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__72__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__72__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__73__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__73__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__74__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__74__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__75__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__75__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__75__y0;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__75__h;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__79__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__79__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__80__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__80__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__81__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__81__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__82__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__82__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__82__y0;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__82__h;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__86__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__86__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__87__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__87__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__88__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__88__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__89__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__89__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__89__y0;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__89__h;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__93__x;
    };
    struct {
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__93__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__94__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__94__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__95__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__95__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__96__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__96__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__96__y0;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__96__h;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__100__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__100__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__101__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__on_border__101__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__102__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__102__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__103__x;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__103__y;
        SData/*9:0*/ __Vfunc_top_tinyfarm_sim__DOT__in_rect__103__w;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*0:0*/, 4> top_tinyfarm_sim__DOT__field_valid;
        VlUnpacked<CData/*0:0*/, 4> top_tinyfarm_sim__DOT__field_ready;
        VlUnpacked<CData/*1:0*/, 4> top_tinyfarm_sim__DOT__field_crop;
        VlUnpacked<CData/*2:0*/, 4> top_tinyfarm_sim__DOT__field_timer;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vtop_tinyfarm_sim__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtop_tinyfarm_sim___024root(Vtop_tinyfarm_sim__Syms* symsp, const char* namep);
    ~Vtop_tinyfarm_sim___024root();
    VL_UNCOPYABLE(Vtop_tinyfarm_sim___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
